INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Abreu e Lima");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Afogados da Ingazeira");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Afrânio");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Agrestina");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Água Preta");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Águas Belas");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Alagoinha");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Aliança");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Altinho");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Amaraji");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Angelim");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Araçoiaba");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Araripina");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Arcoverde");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Barra de Guabiraba");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Barreiros");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Belém de Maria");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Belém do São Francisco");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Belo Jardim");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Betânia");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Bezerros");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Bodocó");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Bom Conselho");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Bom Jardim");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Bonito");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Brejão");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Brejinho");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Brejo da Madre de Deus");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Buenos Aires");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Buíque");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Cabo de Santo Agostinho");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Cabrobó");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Cachoeirinha");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Caetés");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Calçado");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Calumbi");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Camaragibe");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Camocim de São Félix");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Camutanga");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Canhotinho");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Capoeiras");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Carnaíba");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Carnaubeira da Penha");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Carpina");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Caruaru");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Casinhas");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Catende");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Cedro");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Chã de Alegria");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Chã Grande");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Condado");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Correntes");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Cortês");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Cumaru");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Cupira");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Custódia");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Dormentes");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Escada");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Exu");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Feira Nova");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Fernando de Noronha");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Ferreiros");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Flores");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Floresta");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Frei Miguelinho");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Gameleira");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Garanhuns");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Glória do Goitá");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Goiana");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Granito");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Gravatá");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Iati");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Ibimirim");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Ibirajuba");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Igarassu");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Iguaraci");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Ilha de Itamaracá");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Inajá");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Ingazeira");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Ipojuca");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Ipubi");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Itacuruba");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Itaíba");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Itambé");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Itapetim");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Itapissuma");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Itaquitinga");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Jaboatão dos Guararapes");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Jaqueira");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Jataúba");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Jatobá");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("João Alfredo");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Joaquim Nabuco");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Jucati");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Jupi");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Jurema");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Lagoa do Carro");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Lagoa do Itaenga");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Lagoa do Ouro");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Lagoa dos Gatos");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Lagoa Grande");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Lajedo");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Limoeiro");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Macaparana");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Machados");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Manari");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Maraial");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Mirandiba");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Moreilândia");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Moreno");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Nazaré da Mata");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Olinda");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Orobó");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Orocó");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Ouricuri");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Palmares");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Palmeirina");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Panelas");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Paranatama");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Parnamirim");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Passira");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Paudalho");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Paulista");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Pedra");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Pesqueira");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Petrolândia");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Petrolina");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Poção");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Pombos");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Primavera");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Quipapá");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Quixaba");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Recife");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Riacho das Almas");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Ribeirão");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Rio Formoso");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Sairé");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Salgadinho");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Salgueiro");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Saloá");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Sanharó");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Santa Cruz");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Santa Cruz da Baixa Verde");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Santa Cruz do Capibaribe");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Santa Filomena");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Santa Maria da Boa Vista");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Santa Maria do Cambucá");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Santa Terezinha");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("São Benedito do Sul");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("São Bento do Una");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("São Caetano");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("São João");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("São Joaquim do Monte");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("São José da Coroa Grande");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("São José do Belmonte");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("São José do Egito");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("São Lourenço da Mata");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("São Vicente Férrer");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Serra Talhada");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Serrita");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Sertânia");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Sirinhaém");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Solidão");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Surubim");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Tabira");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Tacaimbó");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Tacaratu");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Tamandaré");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Taquaritinga do Norte");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Terezinha");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Terra Nova");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Timbaúba");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Toritama");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Tracunhaém");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Trindade");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Triunfo");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Tupanatinga");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Tuparetama");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Venturosa");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Verdejante");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Vertente do Lério");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Vertentes");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Vicência");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Vitória de Santo Antão");
INSERT INTO `prnmbc1`.`city` (`name`) VALUES ("Xexéu");

INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Administrativo");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Agricultura, Pecuária, Veterinária");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Alta Direção, Planejamento Estratégico");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Arquitetura, Decoração, Design");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Atendimento a Clientes");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Ciências, Pesquisa");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Comercial, Vendas");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Comércio Exterior, Importação, Exportação");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Compras");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Comunicação, TV, Cinema");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Construção, Manutenção");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Consultoria");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Contábil, Finanças, Economia");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Controle de Qualidade");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Cultura, Lazer, Entretenimento");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Educação Fí­sica, Esportes");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Educação, Ensino, Idiomas");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Engenharia");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Informática, TI, Telecomunicações");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Jurí­dica");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Logí­stica, Suprimentos, Armazém");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Marketing");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Mecânica");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Meio Ambiente, Ecologia");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Moda");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Não informada");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Produção");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Quí­mica, Petroquí­mica");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Recepcionista");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Recursos Humanos");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Restaurante");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Saúde");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Segurança, Vigilância");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Serviços Gerais, Domiciliares, Limpeza");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Serviços Sociais e Comunitários");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Setor Imobiliário");
INSERT INTO `prnmbc1`.`occupation` (`name`) VALUES ("Telemarketing");